"""Generate a hosts blocklist from one-domain-per-line input."""
import argparse, re, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from safestack_common import atomic_write, read_regular

DOMAIN = re.compile(r"(?=.{1,253}\Z)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}\Z", re.I)

def generate(source, output):
    domains=[]
    with open(source,encoding='utf-8', errors='strict') as source_file:
        for line in source_file:
            line=line.strip().lower()
            if line and not line.startswith('#') and DOMAIN.fullmatch(line):
                domains.append(line)
    unique = sorted(set(domains))
    data = '# Generated by SafeStack DNS Shield\n' + ''.join(f'0.0.0.0 {d}\n' for d in unique)
    atomic_write(output, data.encode(), 0o644)
    return len(unique)
if __name__=='__main__':
    p=argparse.ArgumentParser(); p.add_argument('source'); p.add_argument('output'); x=p.parse_args(); print(f'Wrote {generate(x.source,x.output)} domains')
