"""Generate a hosts blocklist from one-domain-per-line input."""
import argparse

def generate(source, output):
    domains=[]
    with open(source,encoding='utf-8') as source_file:
        for line in source_file:
            line=line.strip().lower()
            if line and not line.startswith('#') and ' ' not in line and '/' not in line and '.' in line:
                domains.append(line)
    with open(output,'w',encoding='utf-8') as f:
        f.write('# Generated by SafeStack DNS Shield\n'); f.writelines(f'0.0.0.0 {d}\n' for d in sorted(set(domains)))
    return len(set(domains))
if __name__=='__main__':
    p=argparse.ArgumentParser(); p.add_argument('source'); p.add_argument('output'); x=p.parse_args(); print(f'Wrote {generate(x.source,x.output)} domains')
